services: 
  frontend: 
    build: 
      context: .
      dockerfile: front/Dockerfile
    ports: 
      - "3000:3000"
    environment: 
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on: 
      - backend 
    networks: 
      - app-network 

  backend: 
    build: 
      context: . 
      dockerfile: back/Dockerfile
    ports: 
      - "8080:8080"
    environment: 
      - SPRING_PROFILES_ACTIVE=docker
    networks: 
      - app-network

networks:
  app-network: 
    driver: bridge
